### ISSUE TITLE
geforce.cc fail to build on gcc 4.2 (Leopard ppc32), other errors

### ISSUE THREAD

**Issue by Randrianasulu** [bochs-emu/Bochs#765]
more complete configure like I use on Termux

./configure --with-x11 --without-carbon --enable-usb --enable-ne2000 --enable-clgd54xx --enable-voodoo --enable-sb16 --enable-es1370 --with-sdl2 --enable-usb-ohci --enable-usb-xhci --enable-usb-ehci --enable-all-optimizations --enable-geforce      

resulted in 

```
cd iodev/display && \
        make  libdisplay.a                                                                         g++-4.2 -c   -I.. -I../.. -I./.. -I./../.. -I../../instrument/stubs -I./../../instrument/stubs  -fpascal-strings -fno-common -Wno-four-char-constants -Wno-unknown-pragmas -Dmacintosh -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES    -I/opt/local/include/SDL2 -D_THREAD_SAFE  geforce.cc -o geforce.o        geforce.cc: In member function ‘virtual bool bx_geforce_c::init_vga_extension()’:                  geforce.cc:171: error: ‘nullptr’ was not declared in this scope
geforce.cc: In static member function ‘static void bx_geforce_c::execute_gdi(gf_channel*, Bit32u, Bit32u, Bit32u)’:
geforce.cc:5607: error: ‘nullptr’ was not declared in this scope                                   geforce.cc:5619: error: ‘nullptr’ was not declared in this scope
geforce.cc:5645: error: ‘nullptr’ was not declared in this scope                                   geforce.cc:5657: error: ‘nullptr’ was not declared in this scope
geforce.cc: In static member function ‘static void bx_geforce_c::execute_iifc(gf_channel*, Bit32u, Bit32u)’:                                                                                          geforce.cc:5888: error: ‘nullptr’ was not declared in this scope                                   geforce.cc:5900: error: ‘nullptr’ was not declared in this scope
geforce.cc: In static member function ‘static void bx_geforce_c::execute_sifc(gf_channel*, Bit32u, Bit32u)’:
geforce.cc:5927: error: ‘nullptr’ was not declared in this scope                                   geforce.cc:5939: error: ‘nullptr’ was not declared in this scope                                   geforce.cc: In static member function ‘static void bx_geforce_c::execute_tfc(gf_channel*, Bit32u, Bit32u)’:
geforce.cc:5971: error: ‘nullptr’ was not declared in this scope                                   geforce.cc:5985: error: ‘nullptr’ was not declared in this scope
geforce.cc: In static member function ‘static int bx_geforce_c::execute_command(Bit32u, Bit32u, Bit32u, Bit32u)’:
geforce.cc:7062: error: ‘nullptr’ was not declared in this scope                                   geforce.cc:7082: error: ‘nullptr’ was not declared in this scope
make[1]: *** [geforce.o] Error 1
```

**Comment by Randrianasulu** [comment]
second err:

`
In file included from access2.cc:26:                                                               cpu.h:1300: error: ISO C++ forbids initialization of member ‘cpuloop_stack_anchor’                 cpu.h:1300: error: making ‘cpuloop_stack_anchor’ static                                            cpu.h:1300: error: invalid in-class initialization of static data member of non-integral type ‘const volatile Bit8u*’                                                                                 In file included from decoder/fetchdecode32.cc:27:                                                 decoder/../cpu.h:1300: error: ISO C++ forbids initialization of member ‘cpuloop_stack_anchor’      decoder/../cpu.h:1300: error: making ‘cpuloop_stack_anchor’ static                                 decoder/../cpu.h:1300: error: invalid in-class initialization of static data member of non-integral type ‘const volatile Bit8u*’
`

**Comment by stlintel** [comment]
The nullptr keyword was introduced in C++11, which was released in 2011

I don't see why would we bother to support SUCH OLD C++ reincarnations.
Just define yourself nullptr as NULL or upgrade your compiler :)

Same for second error of cpuloop_stack_anchor - I don't plan to rewrite code to be compatible with very old C++.

You may configure with --disable-geforce and --disable-handlers-chaining to work around, I suggest you to research yourself into the code, these workarounds aren't hard to find

**Comment by stlintel** [comment]
GCC 4.8.1 is the first version of the GNU Compiler Collection to achieve full, feature-complete support for the C++11 standard

We probably need to check it configure and disallow attempts to compile with too old compilers which already not supported.

**Comment by stlintel** [comment]
Volker, could we also remove old carbon GUI from source tree ?

**Comment by Randrianasulu** [comment]
you realize compiling new compiler on older OS is not simple, this is not Linux?

I added #define for nullptr, and removed --enable-all-optimizations, so more code compiles but it fails to get pulseaudio headers from/opt/local and having configure args for disabling pulseaudio and also completely disable internal libslirp will be preferable to bumping whole compiler to gcc 4.8+ 

at least for me.

**Comment by Vort** [comment]
> I don't see why would we bother to support SUCH OLD C++ reincarnations.

For example, old compiler support is needed to test Bochs on big endian platforms.
The most accessible way to do this is via emulation.
Building newer compiler there is not the best idea.

> Same for second error of cpuloop_stack_anchor - I don't plan to rewrite code to be compatible with very old C++.

I assume there are very little changes needed to make it work.
Most likely, this initialization in header is the only thing which require fixing.

> ... and also completely disable internal libslirp ...

I noticed problem with slirp when I made builds for Windows 95.
Having flag to disable it will be useful.

**Comment by vruppert** [comment]
The carbon gui can be removed if at least one port of the other guis (e.g. SDL / SDL2) is working properly on the Mac. We should also check whether or not it makes sense to keep the older macintosh gui (for Mac OS 9) in that case.

We should check the compiler capabilities in the configure script and fail there if the default setup of Bochs cannot be build.
Disabling Bochs features in case of an older standard is also an option. In case of the builtin Slirp support it might be useful to add a define that controls the presence of IPv6 support.

**Comment by Vort** [comment]
> In case of the builtin Slirp support it might be useful to add a define that controls the presence of IPv6 support.

Missing IPv6 support is not the only problem with Windows 9x.
Slirp fails there for other reasons as well if I remember correctly.

I think there can be 3 solutions (with increasing complexity):
1. Option to disable slirp during configure;
2. Compile-time ability to disable IPv6;
3. Runtime detection of IPv6 support (via GetProcAddress etc.).

**Comment by Randrianasulu** [comment]
I bite the bullet and compiled Bochs with gcc 14 from ppcports.
It chocked initially on -fpascal-strings in configure, but I edited whole line out of configure.ac and autoreconf.

Configure finished, and after compiling and installing I get this (there was old err about malformed cpu directive at line 220 in .bochrc but I guess everyone just lives with it)

<img width="1280" height="800" alt="Image" src="https://github.com/user-attachments/assets/bfd4719a-33f7-4877-ae2b-2c7dd545a0c4" />

Not sure if blue-ish color of button bar at the top is correct?

**Comment by stlintel** [comment]
When I run latest sources with default provided .bochsrc I don't get any malformed cpu error ...
What do you mean ?
Smth MACOS specific ?
What did you have to edit to make it okay ?

**Comment by Randrianasulu** [comment]
сб, 6 июн. 2026 г., 14:35 Stanislav Shwartsman ***@***.***>:

> *stlintel* left a comment (bochs-emu/Bochs#765)
> <https://github.com/bochs-emu/Bochs/issues/765#issuecomment-4638380938>
>
> When I run latest sources with default provided .bochsrc I don't get any
> malformed cpu error ...
> What do you mean ?
> Smth MACOS specific ?
> What did you have to edit to make it okay ?
>
--- a/bochs/.bochsrc
+++ b/bochs/.bochsrc

@@ -217,7 +217,7 @@

#  2.2.6 2.6Ghz Intel Core 2 Duo with WinXP/g++ 3.4       21 to 25 Mips

 #  2.2.6 2.1Ghz Athlon XP with Linux 2.6/g++ 3.4          12 to 15 Mips

#=======================================================================
-cpu: model=core2_penryn_t9600, count=1, ips=50000000,
reset_on_triple_fault=1, ignore_bad_msrs=1, msrs="msrs.def"

+#cpu: model=core2_penryn_t9600, count=1, ips=50000000,
reset_on_triple_fault=1, ignore_bad_msrs=1,
 msrs="msrs.def"

just commented out cpu: line.

I do not think I limited my cpu choices in configure ?

./configure --with-x11 --without-carbon --enable-usb --enable-ne2000
--enable-clgd54xx --enable-voodoo --enable-sb16 --enable-es1370
--enable-usb-ohci --enable-usb-xhci --enable-usb-ehci --enable-geforce
--without-pulse --with-sdl2 --enable-using-libslirp

**Comment by stlintel** [comment]
You do limit by not including --enable-x86-64
Most of the modern CPU are 64-bit.

**Comment by stlintel** [comment]
> The carbon gui can be removed if at least one port of the other guis (e.g. SDL / SDL2) is working properly on the Mac. We should also check whether or not it makes sense to keep the older macintosh gui (for Mac OS 9) in that case.
> 
> We should check the compiler capabilities in the configure script and fail there if the default setup of Bochs cannot be build. Disabling Bochs features in case of an older standard is also an option. In case of the builtin Slirp support it might be useful to add a define that controls the presence of IPv6 support.

So X11 is working, probably time to remove old carbon to avoid confusion.

**Comment by Randrianasulu** [comment]
сб, 6 июн. 2026 г., 15:00 Stanislav Shwartsman ***@***.***>:

> *stlintel* left a comment (bochs-emu/Bochs#765)
> <https://github.com/bochs-emu/Bochs/issues/765#issuecomment-4638473468>
>
> The carbon gui can be removed if at least one port of the other guis (e.g.
> SDL / SDL2) is working properly on the Mac. We should also check whether or
> not it makes sense to keep the older macintosh gui (for Mac OS 9) in that
> case.
>
> We should check the compiler capabilities in the configure script and fail
> there if the default setup of Bochs cannot be build. Disabling Bochs
> features in case of an older standard is also an option. In case of the
> builtin Slirp support it might be useful to add a define that controls the
> presence of IPv6 support.
>
> So X11 is working, probably time to remove old carbon to avoid confusion.
>



(semi-rhetorical): why such delete mania?

I prefer to have working example of code, even if it was working some time
ago.
